// Generated by CoffeeScript 1.9.3
(function() {
  var _callback, _url, ec, request, translate;

  request = require('request');

  ec = encodeURIComponent;

  _callback = function(callback) {
    return function(error, res, body) {
      var v;
      if (error) {
        return callback(Error("Net connect error"));
      }
      if (res.statusCode >= 400) {
        return callback(Error("Service error: " + body));
      }
      if (typeof body === 'string') {
        v = (new Function("return " + body))()[0][0][0];
      } else {
        v = body[0][0][0];
      }
      return callback(null, v);
    };
  };

  _url = function(text, source, dest) {
    return "https://translate.google.com/translate_a/single?client=t&sl=" + source + "&tl=" + dest + "&hl=" + dest + "&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&dt=at&ie=UTF-8&oe=UTF-8&pc=1&otf=1&ssel=0&tsel=0&kc=1&tk=96009|481150&q=" + (ec(text));
  };

  translate = function(text, source, dest, callback) {
    return request.get(_url(text, source, dest), _callback(callback));
  };

  translate.langs = ["en", "zh-CN", "zh-TW", "ja"];

  module.exports = translate;

}).call(this);
